name: tank-warriors
adopt-info: meta
summary: Driving, shooting, explosions, and programming - all in one game
description: |
  Driving, shooting, explosions, and programming - all in one game
base: core22
architectures:
- amd64
confinement: strict
grade: stable

apps:
  tank-warriors:
    extensions: [gnome]
    command: tankwarriors/tankwarriors.x86_64
    environment:
      LD_LIBRARY_PATH: "$SNAP/tankwarriors/tankwarriors_data/Plugins/x86_64:$LD_LIBRARY_PATH"
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - joystick
      - network
      - opengl
      - wayland
      - x11

parts:
  meta:
    plugin: nil
    override-build: |
      craftctl default
      craftctl set version="$(curl https://api.github.com/repos/endless-network/TankWarriors_Binary/releases/latest | grep '"tag_name":' | grep -oE "([0-9]+\.[0-9]+)").0"

  tank-warriors:
    source: .
    plugin: nil
    build-packages:
      - unzip
      - wget
      - jq
    override-build: |
      craftctl default
      curl https://api.github.com/repos/endless-network/TankWarriors_Binary/releases/latest | jq -r ".assets[0].browser_download_url" | xargs wget -O tankwarriors.zip
      unzip tankwarriors.zip -d temp
      mkdir -p $CRAFT_PART_INSTALL/tankwarriors
      cp temp/*/*.x86_64 $CRAFT_PART_INSTALL/tankwarriors/tankwarriors.x86_64
      cp -r temp/*/*_Data $CRAFT_PART_INSTALL/tankwarriors/tankwarriors_data
      chmod +x $CRAFT_PART_INSTALL/tankwarriors/tankwarriors.x86_64
      cp -r TW_Favicon_* $CRAFT_PART_INSTALL/tankwarriors
