name: tank-warriors
adopt-info: tank-warriors
base: core22
architectures:
- amd64
confinement: strict
grade: stable

apps:
  tank-warriors:
    extensions: [gnome]
    command: tankwarriors/tankwarriors.x86_64
    common-id: com.endlessnetwork.tankwarriors
    environment:
      LD_LIBRARY_PATH: $SNAP/tankwarriors/tankwarriors_Data/Plugins/x86_64:$SNAP/tankwarriors/tankwarriors_Data/Mono/x86_64:$LD_LIBRARY_PATH
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - joystick
      - network
      - opengl
      - wayland
      - x11

parts:
  tank-warriors:
    plugin: dump
    source: https://github.com/endless-network/TankWarriors_Binary.git
    parse-info: [com.endlessnetwork.tankwarriors.appdata.xml]
    build-packages:
      - unzip
      - wget
      - jq
    override-build: |
      craftctl default
      curl https://api.github.com/repos/endless-network/TankWarriors_Binary/releases/latest | jq -r ".assets[0].browser_download_url" | xargs wget -O tankwarriors.zip
      unzip tankwarriors.zip -d temp
      mkdir -p $CRAFT_PART_INSTALL/tankwarriors
      cp temp/*/*.x86_64 $CRAFT_PART_INSTALL/tankwarriors/tankwarriors.x86_64
      cp -r temp/*/*_Data $CRAFT_PART_INSTALL/tankwarriors/tankwarriors_Data
      chmod +x $CRAFT_PART_INSTALL/tankwarriors/tankwarriors.x86_64
      cp -r TW_Favicon_* $CRAFT_PART_INSTALL/tankwarriors
